name: Build MT798x OpenWrt
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1.拉取当前仓库（读取根目录你的.config配置文件）
      - name: Checkout Repo Config
        uses: actions/checkout@v4

      # 2.安装编译全依赖
      - name: Install Build Dependencies
        run: |
          sudo apt update -qq
          sudo apt install -y build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch python3 unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs gcc-multilib p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler g++-multilib gperf wget curl rsync ccache

      # 3.克隆指定分支源码
      - name: Clone Target Source Code
        run: |
          git clone -b mt798x-mt799x-6.6-mtwifi --single-branch https://github.com/ilove125006436/ziyong.git openwrt
          # 把仓库根目录的.config丢进源码目录
          cp .config openwrt/.config

      # 4.更新安装feeds
      - name: Feeds Update & Install
        run: |
          cd openwrt
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      # 5.适配配置
      - name: Defconfig Adapt
        run: |
          cd openwrt
          make defconfig

      # 6.预下载全部源码包
      - name: Pre Download Source
        run: |
          cd openwrt
          make download -j$(nproc)

      # 7.编译固件
      - name: Build Firmware
        run: |
          cd openwrt
          make -j$(nproc) V=s

      # 8.上传成品固件
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: MT798x-Firmware
          path: openwrt/bin/targets/
